### ISSUE TITLE
마스터즈 코스 - 화이트레벨 소개 수정

### ISSUE THREAD

**Issue by godrm** [code-squad/homepage#2]
시작과정이지만 프로그래밍 입문을 위해 3가지 선택을 할 수 있습니다. 데이터분석기초에서는 Pyhton을 배우고, 웹프론트엔드 개발에서는 JavaScript언어를 배우며, 모바일 애플리케이션에서는 Swift 언어를 배웁니다.
//그림//

위와 같은 구성을 아래처럼 바꿔주세요.

자신이 원하는 프로젝트를 위한 프로그래밍 입문을 위해 아래 3가지 중에 하나를 선택을 할 수 있습니다. 
//그림//
첫 프로그래밍 언어는 아이가 모국어를 배우고 모국어로 생각하는 것과 비슷합니다. 데이터분석 기초에서는 Pyhton을 배우고, 웹프론트엔드 개발에서는 JavaScript언어를 배우며, 모바일 애플리케이션에서는 Swift 언어를 배웁니다.

**Comment by honux77** [comment]
@nigayo 요거 된 건가요?
