### ISSUE TITLE
페이스북에서 og데이터를 올바르게 읽어오지 못함

### ISSUE THREAD

**Issue by HTMLhead** [code-squad/homepage#263]
* 페이스북 에서og데이터를 올바르게 읽어오지 못함
* 존재하지 않는 페이지로 보여진다.

**Comment by dev-angelo** [comment]
### 페이스북에서 홈페이지 디버깅 진행 결과
* 프리코스 외 페이지에서는 og를 정상적으로 불러오고있음.
* 프리코스 관련 페이지에서는 og관련 내용이 없다고 디버깅됨

### 빌드후 각 페이지별로 생성되는 index.html 확인 
* 정상적으로 og데이터가 불러와지는 페이지에서는 `<meta data-react-helmet="true" property="og:url" content="https://codesquad.kr/faq"/>` og:url 이 설정되고있음
* 템플릿으로 생성되는 페이지는 og:url이 `<meta data-react-helmet="true" property="og:url" content="https://codesquad.kr/*"/>` 로 설정되고있는것을 확인

템플릿 생성 페이지에서 og:url을 설정하는 부분을 파악 및 수정 예정

**Comment by dev-angelo** [comment]
### codeTogetherTemplate 컴포넌트 확인
* `export default ({ data, path }: PageProps<ICodeTogetherTemplateProps>) => {` 에서 path값이 `/*`로 넘어오는것을 확인
