### ISSUE TITLE
폰트의 굵기가 미세하게 다르다.

### ISSUE THREAD

**Issue by HTMLhead** [code-squad/homepage#66]
* [폰트문제](https://codesquadkr.slack.com/archives/C2Z4470CV/p1652836501321149?thread_ts=1652782343.844379&cid=C2Z4470CV)

**Comment by dev-angelo** [comment]
### 웹 브라우져에서 Figma에서보다 폰트 굵기가 조금 굵어보이는 문제에 대한 이슈
figma font smoothing으로 검색하면 아래 링크 외에도 다수의 이슈들을 찾을 수 있었음.
* https://forum.figma.com/t/why-does-a-font-weight-in-figma-seem-lighter-than-the-same-weight-in-the-browser/2207
* https://www.reddit.com/r/FigmaDesign/comments/hg8sa0/designs_made_in_figma_and_real_page_look/

### Figma 에서 글자가 얇아보이는 이유
* 개발자 도구를 통하여 -webkit-font-smoothing등의 옵션이 적용되어있나 확인해보려고하였는데 컴포넌트 전체가 Canvas로 렌더링되는 형태라서 확인하지는 못하였음.
* 검색을 통해 확인해보려고하였으나 다른사람들도 Canvas로 렌더링될때 figma내부에서 font smoothing옵션을 적용하지 않았을까라고 추측만 하는 상태

###  Figma의 글자와 같이보이도록 css 설정하는 방법
* https://discourse.webflow.com/t/solved-fonts-rendering-thicker-in-webflow-preview-and-browser-than-in-figma-sketch/175867
* https://fjolt.com/article/css-make-text-look-like-figma

### css 설정 결과
![Comparison](https://user-images.githubusercontent.com/58318174/169742961-c2247231-72d8-4a9f-aa38-f5318f0c3918.png)
비교결과 두 글자가 동일한 두께로 렌더링되는것을 확인.
* 좌측이 Figma에서 보여지는 글자
* 우측이 `-webkit-font-smooting: antialiased;` 옵션을 결과
